name = "whisper"
version = "0.2.0"
description = "Local process pub/sub for Gleam with buffered subscriptions. Cross-platform support for Erlang and JavaScript."
licenses = ["MIT"]
repository = { type = "github", user = "webermarci", repo = "whisper" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[dependencies]
gleam_deque = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.69.0 and < 1.0.0"
