name = "whisper"
version = "0.1.0"
description = "Local process pub/sub for Gleam with buffered subscriptions. Cross-platform support for Erlang and JavaScript."
licenses = ["MIT"]
repository = { type = "github", user = "webermarci", repo = "whisper" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
